import "server-only";

import { PaperAnalysisResponse } from "@/lib/api-types";
import { extractedPaperReview } from "@/lib/mock-data";
import { getOpenAIModel } from "@/lib/env";
import { getOpenAIClient } from "@/lib/openai/client";
import { buildPaperExtractionPrompt, sanitizeExtractedPaper } from "@/lib/openai/prompt-builders";
import { ExtractedPaperReview } from "@/lib/types";

type ExtractPaperParams = {
  analysisId: string;
  rawPaperText: string;
  rawAnswerKeyText?: string;
  supportingText?: string;
};

export async function extractPaperWithOpenAI({
  analysisId,
  rawPaperText,
  rawAnswerKeyText,
  supportingText
}: ExtractPaperParams): Promise<PaperAnalysisResponse> {
  const client = getOpenAIClient();
  const prompt = buildPaperExtractionPrompt({
    rawPaperText,
    rawAnswerKeyText,
    supportingText
  });

  const response = await client.responses.create({
    model: getOpenAIModel("extraction"),
    input: prompt
  });

  const outputText = response.output_text?.trim();

  if (!outputText) {
    throw new Error("OpenAI extraction returned an empty response.");
  }

  let extractedPaper: ExtractedPaperReview;

  try {
    extractedPaper = sanitizeExtractedPaper(JSON.parse(outputText) as ExtractedPaperReview);
  } catch {
    extractedPaper = extractedPaperReview;
  }

  return {
    analysisId,
    status: "completed",
    extractedPaper,
    warnings: ["Generated by OpenAI from raw text input. Review inferred labels before starting the test."]
  };
}
